# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fV87PQSMLt_x3laYPh8tJXBUgewkFsf0
"""

from google.colab import drive
drive.mount('/content/drive')

cd drive/My\ Drive/U-Net/CamVid


!python train.py --num_epochs 2000 --crop_height 320 --crop_width 320 --continue_training True --epoch_start_i 499

ls

!python test.py --epoch_number=0270

pwd

dataset_dir

ls

cd CamVid


